version: "3.3"
services:
  mongodb:
    image: mongo:5.0
    container_name: nextdb
    ports:
      - "27017:27017"
    command: --profile=1 --slowms=1
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbuser
      MONGO_INITDB_ROOT_PASSWORD: dbpass
      MONGO_INITDB_DATABASE: nextNetlify
