[build]
  command = "npm run build"
  publish = "build"
  environment = { NODE_VERSION = "14.13.1" }
 
[dev]
 command = "npm run dev"
 
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"